name: Build and push a CRF-only docker image

on:
  workflow_dispatch:
    inputs:
      custom_tag:
        type: string
        description: Docker image tag
        required: true
        default: "latest-crf"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0
    - uses: clonedSemicolon/setup-strace@v13
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.10+7'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
  docker-build:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Create more disk space
      run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - uses: actions/checkout@v4
    - uses: clonedSemicolon/setup-strace@v13
    - name: Build and push
      id: docker_build
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        dockerfile: Dockerfile.crf
        username: ${{ secrets.DOCKERHUB_USERNAME_LFOPPIANO }}
        password: ${{ secrets.DOCKERHUB_TOKEN_LFOPPIANO }}
        image: lfoppiano/grobid
        registry: docker.io
        pushImage: true
        tags: |
          latest-develop, ${{ github.event.inputs.custom_tag}}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
